######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 12 19:17:06 2013
######################################################################

TEMPLATE = dll
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qt_avisynth.h qt_avisynthdll.h
