######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 7 18:42:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += avisynth.h avisynthdll.h internal.h
SOURCES += AvisynthWrapper.cpp
