#include "LanguageCodes.h"




//using namespace System::Collections::Generic;

//using namespace System::Text;

//using namespace System::Linq;

namespace BDInfo
{

	QVector<KeyValuePair<QString, QString>*> LanguageCodes::GetTopLanguages()
	{
//C# TO C++ CONVERTER TODO TASK: Lambda expressions and anonymous methods are not converted to native C++ unless the option to convert to C++0x lambdas is selected:
	  return GetLanguages().Where(l => l->Key == "chi" || l->Key == "dut" || l->Key == "eng" || l->Key == "fin" || l->Key == "fre" || l->Key == "ger" || l->Key == "ita" || l->Key == "jpn" || l->Key == "nor" || l->Key == "por" || l->Key == "ita" || l->Key == "rus" || l->Key == "spa" || l->Key == "swe")->ToList();
	}

	QVector<KeyValuePair<QString, QString>*> LanguageCodes::GetLanguages()
	{
	  //did not use dictionary in case of duplicates
	  QVector<KeyValuePair<QString, QString>*> langs = QVector<KeyValuePair<QString, QString>*>();
	  langs.push_back(new KeyValuePair<QString, QString>("abk", "Abkhazian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ace", "Achinese"));
	  langs.push_back(new KeyValuePair<QString, QString>("ach", "Acoli"));
	  langs.push_back(new KeyValuePair<QString, QString>("ada", "Adangme"));
	  langs.push_back(new KeyValuePair<QString, QString>("aar", "Afar"));
	  langs.push_back(new KeyValuePair<QString, QString>("afh", "Afrihili"));
	  langs.push_back(new KeyValuePair<QString, QString>("afr", "Afrikaans"));
	  langs.push_back(new KeyValuePair<QString, QString>("afa", "Afro-Asiatic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("aka", "Akan"));
	  langs.push_back(new KeyValuePair<QString, QString>("akk", "Akkadian"));
	  langs.push_back(new KeyValuePair<QString, QString>("alb", "Albanian"));
	  langs.push_back(new KeyValuePair<QString, QString>("sqi", "Albanian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ale", "Aleut"));
	  langs.push_back(new KeyValuePair<QString, QString>("alg", "Algonquian languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("tut", "Altaic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("amh", "Amharic"));
	  langs.push_back(new KeyValuePair<QString, QString>("apa", "Apache languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("ara", "Arabic"));
	  langs.push_back(new KeyValuePair<QString, QString>("arc", "Aramaic"));
	  langs.push_back(new KeyValuePair<QString, QString>("arp", "Arapaho"));
	  langs.push_back(new KeyValuePair<QString, QString>("arn", "Araucanian"));
	  langs.push_back(new KeyValuePair<QString, QString>("arw", "Arawak"));
	  langs.push_back(new KeyValuePair<QString, QString>("arm", "Armenian"));
	  langs.push_back(new KeyValuePair<QString, QString>("hye", "Armenian"));
	  langs.push_back(new KeyValuePair<QString, QString>("art", "Artificial (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("asm", "Assamese"));
	  langs.push_back(new KeyValuePair<QString, QString>("ath", "Athapascan languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("aus", "Australian languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("QMap", "Austronesian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("ava", "Avaric"));
	  langs.push_back(new KeyValuePair<QString, QString>("ave", "Avestan"));
	  langs.push_back(new KeyValuePair<QString, QString>("awa", "Awadhi"));
	  langs.push_back(new KeyValuePair<QString, QString>("aym", "Aymara"));
	  langs.push_back(new KeyValuePair<QString, QString>("aze", "Azerbaijani"));
	  langs.push_back(new KeyValuePair<QString, QString>("ban", "Balinese"));
	  langs.push_back(new KeyValuePair<QString, QString>("bat", "Baltic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("bal", "Baluchi"));
	  langs.push_back(new KeyValuePair<QString, QString>("bam", "Bambara"));
	  langs.push_back(new KeyValuePair<QString, QString>("bai", "Bamileke languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("bad", "Banda"));
	  langs.push_back(new KeyValuePair<QString, QString>("bnt", "Bantu (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("bas", "Basa"));
	  langs.push_back(new KeyValuePair<QString, QString>("bak", "Bashkir"));
	  langs.push_back(new KeyValuePair<QString, QString>("baq", "Basque"));
	  langs.push_back(new KeyValuePair<QString, QString>("eus", "Basque"));
	  langs.push_back(new KeyValuePair<QString, QString>("btk", "Batak (Indonesia)"));
	  langs.push_back(new KeyValuePair<QString, QString>("bej", "Beja"));
	  langs.push_back(new KeyValuePair<QString, QString>("bel", "Belarusian"));
	  langs.push_back(new KeyValuePair<QString, QString>("bem", "Bemba"));
	  langs.push_back(new KeyValuePair<QString, QString>("ben", "Bengali"));
	  langs.push_back(new KeyValuePair<QString, QString>("ber", "Berber (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("bho", "Bhojpuri"));
	  langs.push_back(new KeyValuePair<QString, QString>("bih", "Bihari"));
	  langs.push_back(new KeyValuePair<QString, QString>("bik", "Bikol"));
	  langs.push_back(new KeyValuePair<QString, QString>("bin", "Bini"));
	  langs.push_back(new KeyValuePair<QString, QString>("bis", "Bislama"));
	  langs.push_back(new KeyValuePair<QString, QString>("bos", "Bosnian"));
	  langs.push_back(new KeyValuePair<QString, QString>("bra", "Braj"));
	  langs.push_back(new KeyValuePair<QString, QString>("bre", "Breton"));
	  langs.push_back(new KeyValuePair<QString, QString>("bug", "Buginese"));
	  langs.push_back(new KeyValuePair<QString, QString>("bul", "Bulgarian"));
	  langs.push_back(new KeyValuePair<QString, QString>("bua", "Buriat"));
	  langs.push_back(new KeyValuePair<QString, QString>("bur", "Burmese"));
	  langs.push_back(new KeyValuePair<QString, QString>("mya", "Burmese"));
	  langs.push_back(new KeyValuePair<QString, QString>("cad", "Caddo"));
	  langs.push_back(new KeyValuePair<QString, QString>("car", "Carib"));
	  langs.push_back(new KeyValuePair<QString, QString>("cat", "Catalan"));
	  langs.push_back(new KeyValuePair<QString, QString>("cau", "Caucasian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("ceb", "Cebuano"));
	  langs.push_back(new KeyValuePair<QString, QString>("cel", "Celtic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("cai", "Central American Indian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("chg", "Chagatai"));
	  langs.push_back(new KeyValuePair<QString, QString>("cmc", "Chamic languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("cha", "Chamorro"));
	  langs.push_back(new KeyValuePair<QString, QString>("che", "Chechen"));
	  langs.push_back(new KeyValuePair<QString, QString>("chr", "Cherokee"));
	  langs.push_back(new KeyValuePair<QString, QString>("chy", "Cheyenne"));
	  langs.push_back(new KeyValuePair<QString, QString>("chb", "Chibcha"));
	  langs.push_back(new KeyValuePair<QString, QString>("chi", "Chinese"));
	  langs.push_back(new KeyValuePair<QString, QString>("zho", "Chinese"));
	  langs.push_back(new KeyValuePair<QString, QString>("chn", "Chinook jargon"));
	  langs.push_back(new KeyValuePair<QString, QString>("chp", "Chipewyan"));
	  langs.push_back(new KeyValuePair<QString, QString>("cho", "Choctaw"));
	  langs.push_back(new KeyValuePair<QString, QString>("chu", "Church Slavic"));
	  langs.push_back(new KeyValuePair<QString, QString>("chk", "Chuukese"));
	  langs.push_back(new KeyValuePair<QString, QString>("chv", "Chuvash"));
	  langs.push_back(new KeyValuePair<QString, QString>("cop", "Coptic"));
	  langs.push_back(new KeyValuePair<QString, QString>("cor", "Cornish"));
	  langs.push_back(new KeyValuePair<QString, QString>("cos", "Corsican"));
	  langs.push_back(new KeyValuePair<QString, QString>("cre", "Cree"));
	  langs.push_back(new KeyValuePair<QString, QString>("mus", "Creek"));
	  langs.push_back(new KeyValuePair<QString, QString>("crp", "Creoles and pidgins (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("cpe", "Creoles and pidgins,"));
	  langs.push_back(new KeyValuePair<QString, QString>("cpf", "Creoles and pidgins,"));
	  langs.push_back(new KeyValuePair<QString, QString>("cpp", "Creoles and pidgins,"));
	  langs.push_back(new KeyValuePair<QString, QString>("scr", "Croatian"));
	  langs.push_back(new KeyValuePair<QString, QString>("hrv", "Croatian"));
	  langs.push_back(new KeyValuePair<QString, QString>("cus", "Cushitic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("cze", "Czech"));
	  langs.push_back(new KeyValuePair<QString, QString>("ces", "Czech"));
	  langs.push_back(new KeyValuePair<QString, QString>("dak", "Dakota"));
	  langs.push_back(new KeyValuePair<QString, QString>("dan", "Danish"));
	  langs.push_back(new KeyValuePair<QString, QString>("day", "Dayak"));
	  langs.push_back(new KeyValuePair<QString, QString>("del", "Delaware"));
	  langs.push_back(new KeyValuePair<QString, QString>("din", "Dinka"));
	  langs.push_back(new KeyValuePair<QString, QString>("div", "Divehi"));
	  langs.push_back(new KeyValuePair<QString, QString>("doi", "Dogri"));
	  langs.push_back(new KeyValuePair<QString, QString>("dgr", "Dogrib"));
	  langs.push_back(new KeyValuePair<QString, QString>("dra", "Dravidian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("dua", "Duala"));
	  langs.push_back(new KeyValuePair<QString, QString>("dut", "Dutch"));
	  langs.push_back(new KeyValuePair<QString, QString>("nld", "Dutch"));
	  langs.push_back(new KeyValuePair<QString, QString>("dum", "Dutch, Middle (ca. 1050-1350)"));
	  langs.push_back(new KeyValuePair<QString, QString>("dyu", "Dyula"));
	  langs.push_back(new KeyValuePair<QString, QString>("dzo", "Dzongkha"));
	  langs.push_back(new KeyValuePair<QString, QString>("efi", "Efik"));
	  langs.push_back(new KeyValuePair<QString, QString>("egy", "Egyptian (Ancient)"));
	  langs.push_back(new KeyValuePair<QString, QString>("eka", "Ekajuk"));
	  langs.push_back(new KeyValuePair<QString, QString>("elx", "Elamite"));
	  langs.push_back(new KeyValuePair<QString, QString>("eng", "English"));
	  langs.push_back(new KeyValuePair<QString, QString>("enm", "English, Middle (1100-1500)"));
	  langs.push_back(new KeyValuePair<QString, QString>("ang", "English, Old (ca.450-1100)"));
	  langs.push_back(new KeyValuePair<QString, QString>("epo", "Esperanto"));
	  langs.push_back(new KeyValuePair<QString, QString>("est", "Estonian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ewe", "Ewe"));
	  langs.push_back(new KeyValuePair<QString, QString>("ewo", "Ewondo"));
	  langs.push_back(new KeyValuePair<QString, QString>("fan", "Fang"));
	  langs.push_back(new KeyValuePair<QString, QString>("fat", "Fanti"));
	  langs.push_back(new KeyValuePair<QString, QString>("fao", "Faroese"));
	  langs.push_back(new KeyValuePair<QString, QString>("fij", "Fijian"));
	  langs.push_back(new KeyValuePair<QString, QString>("fin", "Finnish"));
	  langs.push_back(new KeyValuePair<QString, QString>("fiu", "Finno-Ugrian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("fon", "Fon"));
	  langs.push_back(new KeyValuePair<QString, QString>("fre", "French"));
	  langs.push_back(new KeyValuePair<QString, QString>("fra", "French"));
	  langs.push_back(new KeyValuePair<QString, QString>("frm", "French, Middle (ca.1400-1600)"));
	  langs.push_back(new KeyValuePair<QString, QString>("fro", "French, Old (842-ca.1400)"));
	  langs.push_back(new KeyValuePair<QString, QString>("fry", "Frisian"));
	  langs.push_back(new KeyValuePair<QString, QString>("fur", "Friulian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ful", "Fulah"));
	  langs.push_back(new KeyValuePair<QString, QString>("gaa", "Ga"));
	  langs.push_back(new KeyValuePair<QString, QString>("glg", "Gallegan"));
	  langs.push_back(new KeyValuePair<QString, QString>("lug", "Ganda"));
	  langs.push_back(new KeyValuePair<QString, QString>("gay", "Gayo"));
	  langs.push_back(new KeyValuePair<QString, QString>("gba", "Gbaya"));
	  langs.push_back(new KeyValuePair<QString, QString>("gez", "Geez"));
	  langs.push_back(new KeyValuePair<QString, QString>("geo", "Georgian"));
	  langs.push_back(new KeyValuePair<QString, QString>("kat", "Georgian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ger", "German"));
	  langs.push_back(new KeyValuePair<QString, QString>("deu", "German"));
	  langs.push_back(new KeyValuePair<QString, QString>("nds", "Saxon"));
	  langs.push_back(new KeyValuePair<QString, QString>("gmh", "German, Middle High (ca.1050-1500)"));
	  langs.push_back(new KeyValuePair<QString, QString>("goh", "German, Old High (ca.750-1050)"));
	  langs.push_back(new KeyValuePair<QString, QString>("gem", "Germanic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("gil", "Gilbertese"));
	  langs.push_back(new KeyValuePair<QString, QString>("gon", "Gondi"));
	  langs.push_back(new KeyValuePair<QString, QString>("gor", "Gorontalo"));
	  langs.push_back(new KeyValuePair<QString, QString>("got", "Gothic"));
	  langs.push_back(new KeyValuePair<QString, QString>("grb", "Grebo"));
	  langs.push_back(new KeyValuePair<QString, QString>("grc", "Greek, Ancient (to 1453)"));
	  langs.push_back(new KeyValuePair<QString, QString>("gre", "Greek"));
	  langs.push_back(new KeyValuePair<QString, QString>("ell", "Greek"));
	  langs.push_back(new KeyValuePair<QString, QString>("grn", "Guarani"));
	  langs.push_back(new KeyValuePair<QString, QString>("guj", "Gujarati"));
	  langs.push_back(new KeyValuePair<QString, QString>("gwi", "Gwich´in"));
	  langs.push_back(new KeyValuePair<QString, QString>("hai", "Haida"));
	  langs.push_back(new KeyValuePair<QString, QString>("hau", "Hausa"));
	  langs.push_back(new KeyValuePair<QString, QString>("haw", "Hawaiian"));
	  langs.push_back(new KeyValuePair<QString, QString>("heb", "Hebrew"));
	  langs.push_back(new KeyValuePair<QString, QString>("her", "Herero"));
	  langs.push_back(new KeyValuePair<QString, QString>("hil", "Hiligaynon"));
	  langs.push_back(new KeyValuePair<QString, QString>("him", "Himachali"));
	  langs.push_back(new KeyValuePair<QString, QString>("hin", "Hindi"));
	  langs.push_back(new KeyValuePair<QString, QString>("hmo", "Hiri Motu"));
	  langs.push_back(new KeyValuePair<QString, QString>("hit", "Hittite"));
	  langs.push_back(new KeyValuePair<QString, QString>("hmn", "Hmong"));
	  langs.push_back(new KeyValuePair<QString, QString>("hun", "Hungarian"));
	  langs.push_back(new KeyValuePair<QString, QString>("hup", "Hupa"));
	  langs.push_back(new KeyValuePair<QString, QString>("iba", "Iban"));
	  langs.push_back(new KeyValuePair<QString, QString>("ice", "Icelandic"));
	  langs.push_back(new KeyValuePair<QString, QString>("isl", "Icelandic"));
	  langs.push_back(new KeyValuePair<QString, QString>("ibo", "Igbo"));
	  langs.push_back(new KeyValuePair<QString, QString>("ijo", "Ijo"));
	  langs.push_back(new KeyValuePair<QString, QString>("ilo", "Iloko"));
	  langs.push_back(new KeyValuePair<QString, QString>("inc", "Indic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("ine", "Indo-European (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("ind", "Indonesian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ina", "Interlingua (International"));
	  langs.push_back(new KeyValuePair<QString, QString>("ile", "Interlingue"));
	  langs.push_back(new KeyValuePair<QString, QString>("iku", "Inuktitut"));
	  langs.push_back(new KeyValuePair<QString, QString>("ipk", "Inupiaq"));
	  langs.push_back(new KeyValuePair<QString, QString>("ira", "Iranian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("gle", "Irish"));
	  langs.push_back(new KeyValuePair<QString, QString>("mga", "Irish, Middle (900-1200)"));
	  langs.push_back(new KeyValuePair<QString, QString>("sga", "Irish, Old (to 900)"));
	  langs.push_back(new KeyValuePair<QString, QString>("iro", "Iroquoian languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("ita", "Italian"));
	  langs.push_back(new KeyValuePair<QString, QString>("jpn", "Japanese"));
	  langs.push_back(new KeyValuePair<QString, QString>("jav", "Javanese"));
	  langs.push_back(new KeyValuePair<QString, QString>("jrb", "Judeo-Arabic"));
	  langs.push_back(new KeyValuePair<QString, QString>("jpr", "Judeo-Persian"));
	  langs.push_back(new KeyValuePair<QString, QString>("kab", "Kabyle"));
	  langs.push_back(new KeyValuePair<QString, QString>("kac", "Kachin"));
	  langs.push_back(new KeyValuePair<QString, QString>("kal", "Kalaallisut"));
	  langs.push_back(new KeyValuePair<QString, QString>("kam", "Kamba"));
	  langs.push_back(new KeyValuePair<QString, QString>("kan", "Kannada"));
	  langs.push_back(new KeyValuePair<QString, QString>("kau", "Kanuri"));
	  langs.push_back(new KeyValuePair<QString, QString>("kaa", "Kara-Kalpak"));
	  langs.push_back(new KeyValuePair<QString, QString>("kar", "Karen"));
	  langs.push_back(new KeyValuePair<QString, QString>("kas", "Kashmiri"));
	  langs.push_back(new KeyValuePair<QString, QString>("kaw", "Kawi"));
	  langs.push_back(new KeyValuePair<QString, QString>("kaz", "Kazakh"));
	  langs.push_back(new KeyValuePair<QString, QString>("kha", "Khasi"));
	  langs.push_back(new KeyValuePair<QString, QString>("khm", "Khmer"));
	  langs.push_back(new KeyValuePair<QString, QString>("khi", "Khoisan (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("kho", "Khotanese"));
	  langs.push_back(new KeyValuePair<QString, QString>("kik", "Kikuyu"));
	  langs.push_back(new KeyValuePair<QString, QString>("kmb", "Kimbundu"));
	  langs.push_back(new KeyValuePair<QString, QString>("kin", "Kinyarwanda"));
	  langs.push_back(new KeyValuePair<QString, QString>("kir", "Kirghiz"));
	  langs.push_back(new KeyValuePair<QString, QString>("kom", "Komi"));
	  langs.push_back(new KeyValuePair<QString, QString>("kon", "Kongo"));
	  langs.push_back(new KeyValuePair<QString, QString>("kok", "Konkani"));
	  langs.push_back(new KeyValuePair<QString, QString>("kor", "Korean"));
	  langs.push_back(new KeyValuePair<QString, QString>("kos", "Kosraean"));
	  langs.push_back(new KeyValuePair<QString, QString>("kpe", "Kpelle"));
	  langs.push_back(new KeyValuePair<QString, QString>("kro", "Kru"));
	  langs.push_back(new KeyValuePair<QString, QString>("kua", "Kuanyama"));
	  langs.push_back(new KeyValuePair<QString, QString>("kum", "Kumyk"));
	  langs.push_back(new KeyValuePair<QString, QString>("kur", "Kurdish"));
	  langs.push_back(new KeyValuePair<QString, QString>("kru", "Kurukh"));
	  langs.push_back(new KeyValuePair<QString, QString>("kut", "Kutenai"));
	  langs.push_back(new KeyValuePair<QString, QString>("lad", "Ladino"));
	  langs.push_back(new KeyValuePair<QString, QString>("lah", "Lahnda"));
	  langs.push_back(new KeyValuePair<QString, QString>("lam", "Lamba"));
	  langs.push_back(new KeyValuePair<QString, QString>("lao", "Lao"));
	  langs.push_back(new KeyValuePair<QString, QString>("lat", "Latin"));
	  langs.push_back(new KeyValuePair<QString, QString>("lav", "Latvian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ltz", "Letzeburgesch"));
	  langs.push_back(new KeyValuePair<QString, QString>("lez", "Lezghian"));
	  langs.push_back(new KeyValuePair<QString, QString>("lin", "Lingala"));
	  langs.push_back(new KeyValuePair<QString, QString>("lit", "Lithuanian"));
	  langs.push_back(new KeyValuePair<QString, QString>("loz", "Lozi"));
	  langs.push_back(new KeyValuePair<QString, QString>("lub", "Luba-Katanga"));
	  langs.push_back(new KeyValuePair<QString, QString>("lua", "Luba-Lulua"));
	  langs.push_back(new KeyValuePair<QString, QString>("lui", "Luiseno"));
	  langs.push_back(new KeyValuePair<QString, QString>("lun", "Lunda"));
	  langs.push_back(new KeyValuePair<QString, QString>("luo", "Luo (Kenya and Tanzania)"));
	  langs.push_back(new KeyValuePair<QString, QString>("lus", "Lushai"));
	  langs.push_back(new KeyValuePair<QString, QString>("mac", "Macedonian"));
	  langs.push_back(new KeyValuePair<QString, QString>("mkd", "Macedonian"));
	  langs.push_back(new KeyValuePair<QString, QString>("mad", "Madurese"));
	  langs.push_back(new KeyValuePair<QString, QString>("mag", "Magahi"));
	  langs.push_back(new KeyValuePair<QString, QString>("mai", "Maithili"));
	  langs.push_back(new KeyValuePair<QString, QString>("mak", "Makasar"));
	  langs.push_back(new KeyValuePair<QString, QString>("mlg", "Malagasy"));
	  langs.push_back(new KeyValuePair<QString, QString>("may", "Malay"));
	  langs.push_back(new KeyValuePair<QString, QString>("msa", "Malay"));
	  langs.push_back(new KeyValuePair<QString, QString>("mal", "Malayalam"));
	  langs.push_back(new KeyValuePair<QString, QString>("mlt", "Maltese"));
	  langs.push_back(new KeyValuePair<QString, QString>("mnc", "Manchu"));
	  langs.push_back(new KeyValuePair<QString, QString>("mdr", "Mandar"));
	  langs.push_back(new KeyValuePair<QString, QString>("man", "Mandingo"));
	  langs.push_back(new KeyValuePair<QString, QString>("mni", "Manipuri"));
	  langs.push_back(new KeyValuePair<QString, QString>("mno", "Manobo languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("glv", "Manx"));
	  langs.push_back(new KeyValuePair<QString, QString>("mao", "Maori"));
	  langs.push_back(new KeyValuePair<QString, QString>("mri", "Maori"));
	  langs.push_back(new KeyValuePair<QString, QString>("mar", "Marathi"));
	  langs.push_back(new KeyValuePair<QString, QString>("chm", "Mari"));
	  langs.push_back(new KeyValuePair<QString, QString>("mah", "Marshall"));
	  langs.push_back(new KeyValuePair<QString, QString>("mwr", "Marwari"));
	  langs.push_back(new KeyValuePair<QString, QString>("mas", "Masai"));
	  langs.push_back(new KeyValuePair<QString, QString>("myn", "Mayan languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("men", "Mende"));
	  langs.push_back(new KeyValuePair<QString, QString>("mic", "Micmac"));
	  langs.push_back(new KeyValuePair<QString, QString>("min", "Minangkabau"));
	  langs.push_back(new KeyValuePair<QString, QString>("mis", "Miscellaneous languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("moh", "Mohawk"));
	  langs.push_back(new KeyValuePair<QString, QString>("mol", "Moldavian"));
	  langs.push_back(new KeyValuePair<QString, QString>("mkh", "Mon-Khmer (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("lol", "Mongo"));
	  langs.push_back(new KeyValuePair<QString, QString>("mon", "Mongolian"));
	  langs.push_back(new KeyValuePair<QString, QString>("mos", "Mossi"));
	  langs.push_back(new KeyValuePair<QString, QString>("mul", "Multiple languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("mun", "Munda languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("nah", "Nahuatl"));
	  langs.push_back(new KeyValuePair<QString, QString>("nau", "Nauru"));
	  langs.push_back(new KeyValuePair<QString, QString>("nav", "Navajo"));
	  langs.push_back(new KeyValuePair<QString, QString>("nde", "Ndebele, North"));
	  langs.push_back(new KeyValuePair<QString, QString>("nbl", "Ndebele, South"));
	  langs.push_back(new KeyValuePair<QString, QString>("ndo", "Ndonga"));
	  langs.push_back(new KeyValuePair<QString, QString>("nep", "Nepali"));
	  langs.push_back(new KeyValuePair<QString, QString>("new", "Newari"));
	  langs.push_back(new KeyValuePair<QString, QString>("nia", "Nias"));
	  langs.push_back(new KeyValuePair<QString, QString>("nic", "Niger-Kordofanian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("ssa", "Nilo-Saharan (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("niu", "Niuean"));
	  langs.push_back(new KeyValuePair<QString, QString>("non", "Norse, Old"));
	  langs.push_back(new KeyValuePair<QString, QString>("nai", "North American Indian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("sme", "Northern Sami"));
	  langs.push_back(new KeyValuePair<QString, QString>("nor", "Norwegian"));
	  langs.push_back(new KeyValuePair<QString, QString>("nob", "Norwegian Bokmål"));
	  langs.push_back(new KeyValuePair<QString, QString>("nno", "Norwegian Nynorsk"));
	  langs.push_back(new KeyValuePair<QString, QString>("nub", "Nubian languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("nym", "Nyamwezi"));
	  langs.push_back(new KeyValuePair<QString, QString>("nya", "Nyanja"));
	  langs.push_back(new KeyValuePair<QString, QString>("nyn", "Nyankole"));
	  langs.push_back(new KeyValuePair<QString, QString>("nyo", "Nyoro"));
	  langs.push_back(new KeyValuePair<QString, QString>("nzi", "Nzima"));
	  langs.push_back(new KeyValuePair<QString, QString>("oci", "Occitan"));
	  langs.push_back(new KeyValuePair<QString, QString>("oji", "Ojibwa"));
	  langs.push_back(new KeyValuePair<QString, QString>("ori", "Oriya"));
	  langs.push_back(new KeyValuePair<QString, QString>("orm", "Oromo"));
	  langs.push_back(new KeyValuePair<QString, QString>("osa", "Osage"));
	  langs.push_back(new KeyValuePair<QString, QString>("oss", "Ossetian"));
	  langs.push_back(new KeyValuePair<QString, QString>("oto", "Otomian languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("pal", "Pahlavi"));
	  langs.push_back(new KeyValuePair<QString, QString>("pau", "Palauan"));
	  langs.push_back(new KeyValuePair<QString, QString>("pli", "Pali"));
	  langs.push_back(new KeyValuePair<QString, QString>("pam", "Pampanga"));
	  langs.push_back(new KeyValuePair<QString, QString>("pag", "Pangasinan"));
	  langs.push_back(new KeyValuePair<QString, QString>("pan", "Panjabi"));
	  langs.push_back(new KeyValuePair<QString, QString>("pap", "Papiamento"));
	  langs.push_back(new KeyValuePair<QString, QString>("paa", "Papuan (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("per", "Persian"));
	  langs.push_back(new KeyValuePair<QString, QString>("fas", "Persian"));
	  langs.push_back(new KeyValuePair<QString, QString>("peo", "Persian, Old (ca.600-400 B.C.)"));
	  langs.push_back(new KeyValuePair<QString, QString>("phi", "Philippine (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("phn", "Phoenician"));
	  langs.push_back(new KeyValuePair<QString, QString>("pon", "Pohnpeian"));
	  langs.push_back(new KeyValuePair<QString, QString>("pol", "Polish"));
	  langs.push_back(new KeyValuePair<QString, QString>("por", "Portuguese"));
	  langs.push_back(new KeyValuePair<QString, QString>("pra", "Prakrit languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("pro", "Provençal"));
	  langs.push_back(new KeyValuePair<QString, QString>("pus", "Pushto"));
	  langs.push_back(new KeyValuePair<QString, QString>("que", "Quechua"));
	  langs.push_back(new KeyValuePair<QString, QString>("roh", "Raeto-Romance"));
	  langs.push_back(new KeyValuePair<QString, QString>("raj", "Rajasthani"));
	  langs.push_back(new KeyValuePair<QString, QString>("rap", "Rapanui"));
	  langs.push_back(new KeyValuePair<QString, QString>("rar", "Rarotongan"));
	  langs.push_back(new KeyValuePair<QString, QString>("roa", "Romance (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("rum", "Romanian"));
	  langs.push_back(new KeyValuePair<QString, QString>("ron", "Romanian"));
	  langs.push_back(new KeyValuePair<QString, QString>("rom", "Romany"));
	  langs.push_back(new KeyValuePair<QString, QString>("run", "Rundi"));
	  langs.push_back(new KeyValuePair<QString, QString>("rus", "Russian"));
	  langs.push_back(new KeyValuePair<QString, QString>("sal", "Salishan languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("sam", "Samaritan Aramaic"));
	  langs.push_back(new KeyValuePair<QString, QString>("smi", "Sami languages (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("smo", "Samoan"));
	  langs.push_back(new KeyValuePair<QString, QString>("sad", "Sandawe"));
	  langs.push_back(new KeyValuePair<QString, QString>("sag", "Sango"));
	  langs.push_back(new KeyValuePair<QString, QString>("san", "Sanskrit"));
	  langs.push_back(new KeyValuePair<QString, QString>("sat", "Santali"));
	  langs.push_back(new KeyValuePair<QString, QString>("srd", "Sardinian"));
	  langs.push_back(new KeyValuePair<QString, QString>("sas", "Sasak"));
	  langs.push_back(new KeyValuePair<QString, QString>("sco", "Scots"));
	  langs.push_back(new KeyValuePair<QString, QString>("gla", "Gaelic"));
	  langs.push_back(new KeyValuePair<QString, QString>("sel", "Selkup"));
	  langs.push_back(new KeyValuePair<QString, QString>("sem", "Semitic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("scc", "Serbian"));
	  langs.push_back(new KeyValuePair<QString, QString>("srp", "Serbian"));
	  langs.push_back(new KeyValuePair<QString, QString>("srr", "Serer"));
	  langs.push_back(new KeyValuePair<QString, QString>("shn", "Shan"));
	  langs.push_back(new KeyValuePair<QString, QString>("sna", "Shona"));
	  langs.push_back(new KeyValuePair<QString, QString>("sid", "Sidamo"));
	  langs.push_back(new KeyValuePair<QString, QString>("sgn", "Sign languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("bla", "Siksika"));
	  langs.push_back(new KeyValuePair<QString, QString>("snd", "Sindhi"));
	  langs.push_back(new KeyValuePair<QString, QString>("sin", "Sinhalese"));
	  langs.push_back(new KeyValuePair<QString, QString>("sit", "Sino-Tibetan (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("sio", "Siouan languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("den", "Slave (Athapascan)"));
	  langs.push_back(new KeyValuePair<QString, QString>("sla", "Slavic (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("slo", "Slovak"));
	  langs.push_back(new KeyValuePair<QString, QString>("slk", "Slovak"));
	  langs.push_back(new KeyValuePair<QString, QString>("slv", "Slovenian"));
	  langs.push_back(new KeyValuePair<QString, QString>("sog", "Sogdian"));
	  langs.push_back(new KeyValuePair<QString, QString>("som", "Somali"));
	  langs.push_back(new KeyValuePair<QString, QString>("son", "Songhai"));
	  langs.push_back(new KeyValuePair<QString, QString>("snk", "Soninke"));
	  langs.push_back(new KeyValuePair<QString, QString>("wen", "Sorbian languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("nso", "Sotho, Northern"));
	  langs.push_back(new KeyValuePair<QString, QString>("sot", "Sotho, Southern"));
	  langs.push_back(new KeyValuePair<QString, QString>("sai", "South American Indian (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("spa", "Spanish"));
	  langs.push_back(new KeyValuePair<QString, QString>("suk", "Sukuma"));
	  langs.push_back(new KeyValuePair<QString, QString>("sux", "Sumerian"));
	  langs.push_back(new KeyValuePair<QString, QString>("sun", "Sundanese"));
	  langs.push_back(new KeyValuePair<QString, QString>("sus", "Susu"));
	  langs.push_back(new KeyValuePair<QString, QString>("swa", "Swahili"));
	  langs.push_back(new KeyValuePair<QString, QString>("ssw", "Swati"));
	  langs.push_back(new KeyValuePair<QString, QString>("swe", "Swedish"));
	  langs.push_back(new KeyValuePair<QString, QString>("syr", "Syriac"));
	  langs.push_back(new KeyValuePair<QString, QString>("tgl", "Tagalog"));
	  langs.push_back(new KeyValuePair<QString, QString>("tah", "Tahitian"));
	  langs.push_back(new KeyValuePair<QString, QString>("tai", "Tai (Other)"));
	  langs.push_back(new KeyValuePair<QString, QString>("tgk", "Tajik"));
	  langs.push_back(new KeyValuePair<QString, QString>("tmh", "Tamashek"));
	  langs.push_back(new KeyValuePair<QString, QString>("tam", "Tamil"));
	  langs.push_back(new KeyValuePair<QString, QString>("tat", "Tatar"));
	  langs.push_back(new KeyValuePair<QString, QString>("tel", "Telugu"));
	  langs.push_back(new KeyValuePair<QString, QString>("ter", "Tereno"));
	  langs.push_back(new KeyValuePair<QString, QString>("tet", "Tetum"));
	  langs.push_back(new KeyValuePair<QString, QString>("tha", "Thai"));
	  langs.push_back(new KeyValuePair<QString, QString>("tib", "Tibetan"));
	  langs.push_back(new KeyValuePair<QString, QString>("bod", "Tibetan"));
	  langs.push_back(new KeyValuePair<QString, QString>("tig", "Tigre"));
	  langs.push_back(new KeyValuePair<QString, QString>("tir", "Tigrinya"));
	  langs.push_back(new KeyValuePair<QString, QString>("tem", "Timne"));
	  langs.push_back(new KeyValuePair<QString, QString>("tiv", "Tiv"));
	  langs.push_back(new KeyValuePair<QString, QString>("tli", "Tlingit"));
	  langs.push_back(new KeyValuePair<QString, QString>("tpi", "Tok Pisin"));
	  langs.push_back(new KeyValuePair<QString, QString>("tkl", "Tokelau"));
	  langs.push_back(new KeyValuePair<QString, QString>("tog", "Tonga (Nyasa)"));
	  langs.push_back(new KeyValuePair<QString, QString>("ton", "Tonga (Tonga Islands)"));
	  langs.push_back(new KeyValuePair<QString, QString>("tsi", "Tsimshian"));
	  langs.push_back(new KeyValuePair<QString, QString>("tso", "Tsonga"));
	  langs.push_back(new KeyValuePair<QString, QString>("tsn", "Tswana"));
	  langs.push_back(new KeyValuePair<QString, QString>("tum", "Tumbuka"));
	  langs.push_back(new KeyValuePair<QString, QString>("tur", "Turkish"));
	  langs.push_back(new KeyValuePair<QString, QString>("ota", "Turkish, Ottoman (1500-1928)"));
	  langs.push_back(new KeyValuePair<QString, QString>("tuk", "Turkmen"));
	  langs.push_back(new KeyValuePair<QString, QString>("tvl", "Tuvalu"));
	  langs.push_back(new KeyValuePair<QString, QString>("tyv", "Tuvinian"));
	  langs.push_back(new KeyValuePair<QString, QString>("twi", "Twi"));
	  langs.push_back(new KeyValuePair<QString, QString>("uga", "Ugaritic"));
	  langs.push_back(new KeyValuePair<QString, QString>("uig", "Uighur"));
	  langs.push_back(new KeyValuePair<QString, QString>("ukr", "Ukrainian"));
	  langs.push_back(new KeyValuePair<QString, QString>("umb", "Umbundu"));
	  langs.push_back(new KeyValuePair<QString, QString>("und", "Undetermined"));
	  langs.push_back(new KeyValuePair<QString, QString>("urd", "Urdu"));
	  langs.push_back(new KeyValuePair<QString, QString>("uzb", "Uzbek"));
	  langs.push_back(new KeyValuePair<QString, QString>("vai", "Vai"));
	  langs.push_back(new KeyValuePair<QString, QString>("ven", "Venda"));
	  langs.push_back(new KeyValuePair<QString, QString>("vie", "Vietnamese"));
	  langs.push_back(new KeyValuePair<QString, QString>("vol", "Volapük"));
	  langs.push_back(new KeyValuePair<QString, QString>("vot", "Votic"));
	  langs.push_back(new KeyValuePair<QString, QString>("wak", "Wakashan languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("wal", "Walamo"));
	  langs.push_back(new KeyValuePair<QString, QString>("war", "Waray"));
	  langs.push_back(new KeyValuePair<QString, QString>("was", "Washo"));
	  langs.push_back(new KeyValuePair<QString, QString>("wel", "Welsh"));
	  langs.push_back(new KeyValuePair<QString, QString>("cym", "Welsh"));
	  langs.push_back(new KeyValuePair<QString, QString>("wol", "Wolof"));
	  langs.push_back(new KeyValuePair<QString, QString>("xho", "Xhosa"));
	  langs.push_back(new KeyValuePair<QString, QString>("sah", "Yakut"));
	  langs.push_back(new KeyValuePair<QString, QString>("yao", "Yao"));
	  langs.push_back(new KeyValuePair<QString, QString>("yap", "Yapese"));
	  langs.push_back(new KeyValuePair<QString, QString>("yid", "Yiddish"));
	  langs.push_back(new KeyValuePair<QString, QString>("yor", "Yoruba"));
	  langs.push_back(new KeyValuePair<QString, QString>("ypk", "Yupik languages"));
	  langs.push_back(new KeyValuePair<QString, QString>("znd", "Zande"));
	  langs.push_back(new KeyValuePair<QString, QString>("zap", "Zapotec"));
	  langs.push_back(new KeyValuePair<QString, QString>("zen", "Zenaga"));
	  langs.push_back(new KeyValuePair<QString, QString>("zha", "Zhuang"));
	  langs.push_back(new KeyValuePair<QString, QString>("zul", "Zulu"));
	  langs.push_back(new KeyValuePair<QString, QString>("zun", "Zuni"));
	  return langs;
	}

	QString LanguageCodes::GetName(const QString &code)
	{
//C# TO C++ CONVERTER TODO TASK: Lambda expressions and anonymous methods are not converted to native C++ unless the option to convert to C++0x lambdas is selected:
	  return GetLanguages().Where(l => l->Key == code || l->Key == "und")->First()->Value;
	}
}
