######################################################################
# Automatically generated by qmake (2.01a) la 23. marras 12:44:13 2013
######################################################################

TEMPLATE = LIBS
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += avisynth26.h \
           mingw_avisynth5.h \
           mingw_avisynthdll.h
