######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 7 18:59:35 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AssemblyInfo.h Program.h
SOURCES += AssemblyInfo.cpp Program.cpp
