######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 7 18:57:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += neroraw.h
SOURCES += neroraw.cpp
